// packages/ui-web/src/solid/modal.tsx
/**
 * SolidJS component wrapper for the `<saganta-appkit-modal>` Web Component.
 *
 * Why this exists: the underlying modal is a Web Component, which Solid can
 * render as a custom element, but a typed Solid component feels more
 * idiomatic. This wrapper handles `client` assignment, prop-to-attribute
 * forwarding, event listening, and exposes an imperative `open()` / `close()`
 * API via Solid refs.
 *
 * Usage:
 *
 * ```tsx
 * import { StellarAppKitProvider, StellarAppKitModal } from '@saganta/stellar-appkit/solid';
 * import { createSignal } from 'solid-js';
 *
 * function App() {
 *   return (
 *     <StellarAppKitProvider config={...}>
 *       <StellarAppKitModal mode="auto" theme="dark" />
 *       <ConnectButton />
 *     </StellarAppKitProvider>
 *   );
 * }
 *
 * function ConnectButton() {
 *   let modal: { open: () => void } | undefined;
 *   return <button onClick={() => modal?.open()}>Connect</button>;
 * }
 * ```
 *
 * The modal reads its `client` from the same context as the hooks — so it
 * stays in sync with `<StellarAppKitProvider>`. If you want to use it
 * without a provider, use the raw `<saganta-appkit-modal>` element and
 * set `element.client = appkit` directly.
 *
 * The underlying Web Component is imported as a side-effect of importing
 * this module — so the custom element is registered before any modal mounts.
 */

import {
  createComponent,
  onCleanup,
  onMount,
  splitProps,
  type JSX,
  type Component,
} from 'solid-js';
import { useAppKit } from './index.js';
import {
  type StellarAppKitModalProps,
  type StellarAppKitModalHandle,
  type StellarAppKitModalEvents,
  propsToAttributes,
} from '../ui-web/modal-props.js';
import type { ConnectSession, ConnectError } from '@saganta/stellar-appkit';

// NOTE: We deliberately do NOT import '../ui-web/connect-modal.js' here.
// The Web Component class extends `HTMLElement`, which is undefined in
// pure-Node SSR/test environments. Importing it at module top-level would
// crash server-side rendering.
//
// Consumers must import `@saganta/stellar-appkit/ui-web` once at their
// app entry point to register the `<saganta-appkit-modal>` custom element:
//
//   import '@saganta/stellar-appkit/ui-web';

export type { StellarAppKitModalProps, StellarAppKitModalHandle, StellarAppKitModalEvents };

export interface StellarAppKitModalComponentProps
  extends StellarAppKitModalProps,
    StellarAppKitModalEvents {
  /** Optional children — rendered inside the modal host (rarely needed). */
  children?: JSX.Element;
  /** CSS class name applied to the host element. */
  class?: string;
  /** Inline style applied to the host element (for theme overrides via CSS vars). */
  style?: JSX.CSSProperties;
  /** Called with the imperative handle once the host element mounts. */
  ref?: (handle: StellarAppKitModalHandle) => void;
}

/**
 * `<StellarAppKitModal>` — a Solid component wrapping the underlying
 * `<saganta-appkit-modal>` Web Component.
 *
 * The component:
 * 1. Reads the `StellarAppKit` client from context (via `useAppKit()`).
 * 2. Sets `element.client = client` after mount, so the modal wires up its
 *    internal event listeners and preview handler.
 * 3. Forwards all `StellarAppKitModalProps` to attributes on the Web Component.
 * 4. Subscribes to the modal's CustomEvents and dispatches them as the
 *    `onConnect`, `onDisconnect`, `onError` callbacks.
 * 5. Calls the `ref` prop with an imperative handle containing `open()` /
 *    `close()` / `element`.
 */
export const StellarAppKitModal: Component<StellarAppKitModalComponentProps> = (props) => {
  const client = useAppKit();
  let hostEl: HTMLElement & { client: typeof client | null } | null = null;

  // Split out the callback props so we can register/unregister them
  // independently of the attribute-bearing props.
  const [modalProps, eventProps, rest] = splitProps(
    props,
    ['mode', 'theme', 'branding', 'logoSrc', 'title', 'autoRetryNetwork', 'stellarExpertAvatars'],
    ['onConnect', 'onDisconnect', 'onError']
  );

  onMount(() => {
    if (!hostEl) return;
    hostEl.client = client;

    // Apply initial attributes.
    const attrs = propsToAttributes(modalProps);
    for (const [name, value] of Object.entries(attrs)) {
      hostEl!.setAttribute(name, value);
    }

    // Wire up event listeners. We always register all three; the handlers
    // no-op if the corresponding callback isn't set.
    const onConnect = (e: Event) => eventProps.onConnect?.((e as CustomEvent).detail);
    const onDisconnect = (e: Event) => eventProps.onDisconnect?.((e as CustomEvent).detail);
    const onError = (e: Event) => eventProps.onError?.((e as CustomEvent).detail);
    hostEl.addEventListener('sc-connect', onConnect);
    hostEl.addEventListener('sc-disconnect', onDisconnect);
    hostEl.addEventListener('sc-error', onError);

    onCleanup(() => {
      hostEl?.removeEventListener('sc-connect', onConnect);
      hostEl?.removeEventListener('sc-disconnect', onDisconnect);
      hostEl?.removeEventListener('sc-error', onError);
    });

    // Expose the imperative handle via the `ref` callback prop.
    props.ref?.({
      open: async () => {
        await (hostEl as unknown as { open?: () => Promise<void> })?.open?.();
      },
      close: () => {
        (hostEl as unknown as { close?: () => void })?.close?.();
      },
      get element() {
        return hostEl as HTMLElement & { client: typeof client | null };
      },
    });
  });

  // Solid renders unknown lowercase tags as custom elements by default —
  // no special compiler config needed.
  return createComponent(
    ((('saganta-appkit-modal') as unknown) as Component<Record<string, unknown>>),
    {
      ref: (el: HTMLElement & { client: typeof client | null }) => {
        hostEl = el;
      },
      class: rest.class,
      style: rest.style,
      children: rest.children,
    }
  );
};

export default StellarAppKitModal;

// Local helper types — re-exported for consumers who need them.
export type { ConnectSession, ConnectError };

// packages/core/src/react/modal.tsx
/**
 * React JSX wrapper for the `<saganta-appkit-modal>` Web Component.
 *
 * Why this exists: the underlying modal is a Web Component, which works in
 * any framework but feels unidiomatic in React — you have to manage refs,
 * manually set the `.client` property, and listen for CustomEvents. This
 * component wraps all of that behind a normal JSX component with typed props
 * and an imperative handle (via `ref`).
 *
 * Usage:
 *
 * ```tsx
 * import { StellarAppKitProvider, StellarAppKitModal } from '@saganta/stellar-appkit/react';
 *
 * function App() {
 *   return (
 *     <StellarAppKitProvider config={...}>
 *       <StellarAppKitModal mode="auto" theme="dark" />
 *       <ConnectButton />
 *     </StellarAppKitProvider>
 *   );
 * }
 *
 * function ConnectButton() {
 *   const modalRef = useRef<StellarAppKitModalHandle>(null);
 *   return <button onClick={() => modalRef.current?.open()}>Connect</button>;
 * }
 * ```
 *
 * The modal reads its `client` from the same context as the hooks — so it
 * stays in sync with `<StellarAppKitProvider>`. If you want to use it without
 * a provider, use the raw `<saganta-appkit-modal>` element and set
 * `element.client = appkit` directly.
 *
 * The underlying Web Component is imported as a side-effect of importing
 * this module — so the custom element is registered before any modal mounts.
 */

import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type ReactNode,
} from 'react';
import { useAppKit } from './index.js';
import type { StellarAppKit } from '../index.js';
import {
  type StellarAppKitModalProps,
  type StellarAppKitModalHandle,
  type StellarAppKitModalEvents,
  propsToAttributes,
} from '../ui-web/modal-props.js';

// NOTE: We deliberately do NOT import '../ui-web/connect-modal.js' here.
// The Web Component class extends `HTMLElement`, which is undefined in
// pure-Node SSR/test environments. Importing it at module top-level would
// crash server-side rendering.
//
// Instead, consumers must import `@saganta/stellar-appkit/ui-web` once
// at their app entry point to register the `<saganta-appkit-modal>`
// custom element:
//
//   import '@saganta/stellar-appkit/ui-web';
//
// This keeps the framework wrappers fully SSR-safe and lets bundlers
// tree-shake the Web Component code out of server bundles.

export type { StellarAppKitModalProps, StellarAppKitModalHandle, StellarAppKitModalEvents };

export interface StellarAppKitModalComponentProps
  extends StellarAppKitModalProps,
    StellarAppKitModalEvents {
  /** Optional children — rendered inside the modal host (rarely needed). */
  children?: ReactNode;
  /** CSS class name applied to the host element. */
  className?: string;
  /** Inline style applied to the host element (for theme overrides via CSS vars). */
  style?: React.CSSProperties;
}

/**
 * `<StellarAppKitModal>` — a React component wrapping the underlying
 * `<saganta-appkit-modal>` Web Component.
 *
 * The component:
 * 1. Reads the `StellarAppKit` client from context (via `useAppKit()`).
 * 2. Sets `element.client = client` after mount, so the modal wires up its
 *    internal event listeners and preview handler.
 * 3. Forwards all `StellarAppKitModalProps` to attributes on the Web Component.
 * 4. Subscribes to the modal's CustomEvents and dispatches them as the
 *    `onConnect`, `onDisconnect`, `onError` callbacks.
 * 5. Exposes an imperative handle via `ref` with `open()` / `close()` methods.
 */
export const StellarAppKitModal = forwardRef<
  StellarAppKitModalHandle,
  StellarAppKitModalComponentProps
>(function StellarAppKitModal(props, ref) {
  const client = useAppKit();
  const hostRef = useRef<HTMLElement & { client: StellarAppKit | null } | null>(null);

  // Wire up the client to the host element whenever it changes.
  useEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    el.client = client;
  }, [client]);

  // Forward the props to attributes whenever they change. We do this in an
  // effect (rather than JSX attribute spreading) because React doesn't know
  // how to update Web Component custom attributes reliably across versions
  // — setting them imperatively is the most predictable approach.
  useEffect(() => {
    const el = hostRef.current;
    if (!el) return;
    const attrs = propsToAttributes(props);
    for (const [name, value] of Object.entries(attrs)) {
      el.setAttribute(name, value);
    }
  }, [
    props.mode,
    props.theme,
    props.branding,
    props.logoSrc,
    props.title,
    props.autoRetryNetwork,
    props.stellarExpertAvatars,
  ]);

  // Wire up event listeners. We use CustomEvent capture here because the
  // underlying modal dispatches composed/bubbling events.
  useEffect(() => {
    const el = hostRef.current;
    if (!el) return;

    const unsubscribe: Array<() => void> = [];

    if (props.onConnect) {
      const handler = (e: Event) => props.onConnect?.((e as CustomEvent).detail);
      el.addEventListener('sc-connect', handler);
      unsubscribe.push(() => el.removeEventListener('sc-connect', handler));
    }
    if (props.onDisconnect) {
      const handler = (e: Event) => props.onDisconnect?.((e as CustomEvent).detail);
      el.addEventListener('sc-disconnect', handler);
      unsubscribe.push(() => el.removeEventListener('sc-disconnect', handler));
    }
    if (props.onError) {
      const handler = (e: Event) => props.onError?.((e as CustomEvent).detail);
      el.addEventListener('sc-error', handler);
      unsubscribe.push(() => el.removeEventListener('sc-error', handler));
    }
    return () => unsubscribe.forEach((u) => u());
  }, [props.onConnect, props.onDisconnect, props.onError]);

  // Expose the imperative handle: open()/close()/element.
  useImperativeHandle(
    ref,
    (): StellarAppKitModalHandle => ({
      open: async () => {
        await (hostRef.current as unknown as { open?: () => Promise<void> })?.open?.();
      },
      close: () => {
        (hostRef.current as unknown as { close?: () => void })?.close?.();
      },
      get element() {
        return hostRef.current as HTMLElement & { client: StellarAppKit | null };
      },
    }),
    []
  );

  // JSX doesn't natively know how to render Web Components with TypeScript.
  // We use a lowercase tag name (which React treats as a custom element) and
  // cast the props. The `ref` lets us access the underlying DOM node.
  const HostTag = 'saganta-appkit-modal' as unknown as 'div';
  return (
    <HostTag
      ref={hostRef as never}
      className={props.className}
      style={props.style}
    >
      {props.children}
    </HostTag>
  );
});

// Re-exported above — keep these out of the `React` namespace so they're
// tree-shakeable independently of the component.
export { StellarAppKitModal as default };
